name: msf-lime-test
description: null
credentials:
  michael.bontyes@geneva.msf.org-dhis2:
    name: dhis2
    owner: michael.bontyes@geneva.msf.org
  michael.bontyes@geneva.msf.org-openmrs:
    name: openmrs
    owner: michael.bontyes@geneva.msf.org

collections:
  mosul-metadata-mappings: 
    name: mosul-metadata-mappings
