name: msf-lime-test
description: |
  OpenFn cloud project for workflow testing between MSF and OpenFn teams
credentials:
  michael.bontyes@geneva.msf.org-dhis2:
    name: dhis2
    owner: michael.bontyes@geneva.msf.org
  michael.bontyes@geneva.msf.org-openmrs:
    name: openmrs
    owner: michael.bontyes@geneva.msf.org
